version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: carboncredits
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1106
    container_name: postgres-db

  tallerdos:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/carboncredits
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1106
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - "postgres"
